######################## default configuration ####################
baseURL = "https://proteksiuuite.site/"
title = "PROTEKSI"
theme = "educenter-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "PROTEKSI" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "Web Page PROTEKSI"
author = "PROTEKSI"
# contact info
address = "SMA Negeri 5 Balikpapan, Jalan Abdi Praja, Blok F-1, No. 119, Kelurahan Sepinggan, Kecamatan Balikpapan Selatan, Kota Balikpapan, Provinsi Kalimantan Timur, 76115."
email = "proteksiuuite@gmail.com"
# contact form action
contact_form_action = "https://formspree.io/f/mrgvvrel" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = false

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.png" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us10.list-manage.com/subscribe?u=337f6d9f60aa2942f47709aa9&id=30dca95d83" # replace this url with yours
mailchimp_form_name = "337f6d9f60aa2942f47709aa9" # 

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "-1.242242"
map_longitude = "116.897502"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 3
  
############################# social site ########################
[[params.social]]
title = "tiktok"
icon = "ti-tumblr" # themify icon : https://themify.me/themify-icons
link = "#"


[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/proteksiuuite"



################################### English language #####################################
[Languages.en]
languageName = "en"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "HOME"
# copyright
copyright = "Hak Cipta Â© 2023 SI-PROTEKSI" 



################### navigation ####################

# main menu
[[Languages.en.menu.main]]
name = "Apa itu UU ITE?"
url = "uuite/"
weight = 1

[[Languages.en.menu.main]]
weight = 3
name = "Fitur Belajar"
hasChildren = true

  [[Languages.en.menu.main]]
  parent = "Fitur Belajar"
  name = "game"
  url = "game/"

  [[Languages.en.menu.main]]
  parent = "Fitur Belajar"
  name = "quiz"
  url = "quiz/"

[[Languages.en.menu.main]]
name = "Sosialisasi"
url = "sosialisasi/"
weight = 3

[[Languages.en.menu.main]]
name = "Podcast"
url = "https://open.spotify.com/"
weight = 4


[[Languages.en.menu.main]]
name = "Berita Terbaru"
url = "berita/"
weight = 6
  
[[Languages.en.menu.main]]
name = "Curhat"
url = "contact/"
weight = 7


# footer menu


[[Languages.en.menu.footer]]
name = "Update Terbaru"
url = "update/"

[[Languages.en.menu.footer]]
name = "Instagram"
url = "https://www.instagram.com/proteksi.smala/"


